title: 👋 Hi, Im Murad AlNimri
theme: jekyll-theme-minimal
logo: /assets/img/banner.png
description: MSc Business Analytics | AI & Strategy | Data Analytics · Consulting · Insights
show_downloads: false
